global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'gnmic'
    consul_sd_configs:
      - server: clab-escenariofinal-consul-agent:8500
        services:
          - prometheus-prom-output
