{
 "title": "Dashboard SR Linux",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Estado sistema telemetría",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Uso de CPU en SRL1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "srl_nokia_platform_platform_srl_nokia_platform_control_control_srl_nokia_platform_cpu_cpu_total_instant {source=\"clab-escenariofinal-srl1\"}"
    }
   ]
  },
  {
   "title": "Uso de CPU en SRL2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "srl_nokia_platform_platform_srl_nokia_platform_control_control_srl_nokia_platform_cpu_cpu_total_instant {source=\"clab-escenariofinal-srl2\"}"
    }
   ]
  },
  {
   "title": "Tráfico de salida en ethernet-1/1 de SRL1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "srl_nokia_interfaces_interface_traffic_rate_out_bps {source=\"clab-escenariofinal-srl1\"} and {interface_name=\"ethernet-1/1\"}"
    }
   ]
  },
  {
   "title": "Tráfico de salida en ethernet-1/1 de SRL2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "srl_nokia_interfaces_interface_traffic_rate_out_bps {source=\"clab-escenariofinal-srl2\"} and {interface_name=\"ethernet-1/1\"}"
    }
   ]
  },
  {
   "title": "Tráfico de salida en mgmt0 de SRL1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "srl_nokia_interfaces_interface_traffic_rate_out_bps {source=\"clab-escenariofinal-srl1\"} and {interface_name=\"mgmt0\"}"
    }
   ]
  },
  {
   "title": "Tráfico de salida en mgmt0 de SRL2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "srl_nokia_interfaces_interface_traffic_rate_out_bps {source=\"clab-escenariofinal-srl2\"} and {interface_name=\"mgmt0\"}"
    }
   ]
  }
 ]
}